{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saltedge.authenticator",
    "module": "sdk_core",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_core-1.3.2.aar",
          "url": "sdk_core-1.3.2.aar",
          "size": 96920,
          "sha512": "d4391aa1eb653d3e58127b799d6bbaa074f3037c681fcddb1b263014a458f9371e4332f49a2e0c902e94d6d29b2fbaaaf6fe7f1f4afd48387afd36fc44568d0a",
          "sha256": "d416a919c3d61d6fb586ff1a050b37ed5b218aef6c0446695f2ce9ec98cd078d",
          "sha1": "60a7d2a1d760b1129b80964dc08c76d97ef9d81a",
          "md5": "b3a69d1c4b446595e3cb5047a9f71d38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_core-1.3.2.aar",
          "url": "sdk_core-1.3.2.aar",
          "size": 96920,
          "sha512": "d4391aa1eb653d3e58127b799d6bbaa074f3037c681fcddb1b263014a458f9371e4332f49a2e0c902e94d6d29b2fbaaaf6fe7f1f4afd48387afd36fc44568d0a",
          "sha256": "d416a919c3d61d6fb586ff1a050b37ed5b218aef6c0446695f2ce9ec98cd078d",
          "sha1": "60a7d2a1d760b1129b80964dc08c76d97ef9d81a",
          "md5": "b3a69d1c4b446595e3cb5047a9f71d38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_core-1.3.2-sources.jar",
          "url": "sdk_core-1.3.2-sources.jar",
          "size": 34634,
          "sha512": "c39f44d7c1aa95760316d27b0a5cdbf7f7cf301355aec437873d89d0e3833493c254d72d5db85f769f0b1c4c4977aa61793079431299bfd7b3eb48a374235fd1",
          "sha256": "5d53088d7259c670247947fc802d0e4254b4f9d5679c8007d3a145372f42a52b",
          "sha1": "9d1d72c278cb95bf47f04040b62ba20ff6514b96",
          "md5": "b109f9e5ae7866a4c845e5fa57dfd10a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_core-1.3.2-javadoc.jar",
          "url": "sdk_core-1.3.2-javadoc.jar",
          "size": 574987,
          "sha512": "69bdbc6493dcfaf4743e5c53fa84940fc262925002c1a73378876f8bb85a46b6400fd83722f7ca03744918cc6d64f2c06c71fd2df6df499833cb0b333042cbed",
          "sha256": "e74fdb4717d0ba1e2540030164fd75a649dfde9689aa13da5f28810c9608f2f8",
          "sha1": "3cda5acf3dd3cf91a309f2e8e9b44fe1790afd8b",
          "md5": "b991958c5c959db2ac28c15d5bceace5"
        }
      ]
    }
  ]
}
