{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saltedge.authenticator",
    "module": "sdk_core",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_core-1.3.3.aar",
          "url": "sdk_core-1.3.3.aar",
          "size": 97057,
          "sha512": "ab2911ad202d81e15309e9368a389f92cc64af88851385f3a1c87fa8d1d405b4bd663a8410606a588795b6ea6e1d9a2460f7d0d01396c8a22e1bb1eda92ef1d6",
          "sha256": "7b445e4767f02d39ed3217e5f0b9f04f69e72fb72e0df089bf7c1a2af744a11e",
          "sha1": "7ec5f53b16d5a62c6f7733af145f6f91b9d9ce34",
          "md5": "77c0be8e6ab3d44c440db7c5b64883d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_core-1.3.3.aar",
          "url": "sdk_core-1.3.3.aar",
          "size": 97057,
          "sha512": "ab2911ad202d81e15309e9368a389f92cc64af88851385f3a1c87fa8d1d405b4bd663a8410606a588795b6ea6e1d9a2460f7d0d01396c8a22e1bb1eda92ef1d6",
          "sha256": "7b445e4767f02d39ed3217e5f0b9f04f69e72fb72e0df089bf7c1a2af744a11e",
          "sha1": "7ec5f53b16d5a62c6f7733af145f6f91b9d9ce34",
          "md5": "77c0be8e6ab3d44c440db7c5b64883d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_core-1.3.3-sources.jar",
          "url": "sdk_core-1.3.3-sources.jar",
          "size": 34668,
          "sha512": "eac699915c171f4393d8a1b5e7995d2f55b6bc5323aac7c9289fdcbefe86f3188b218ede6f5d86c5ebefd1e47e3c744df04389e0645520e673452ec06d152a25",
          "sha256": "cb94a6b2b68d339ba86f38af1f0db0f049215ecebca06dc6e93bd917454c196b",
          "sha1": "9b1ad2ba673bec6dc0fd794dae86ac91caf29ffe",
          "md5": "eb457786cb1e29c6a27eaf38486bbc4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_core-1.3.3-javadoc.jar",
          "url": "sdk_core-1.3.3-javadoc.jar",
          "size": 575282,
          "sha512": "1f6c1deef16e3d0f372aee2392f07d5e616403d120a71d13d43bc616929f777759394c92d8b856b377cf1d5b1936dc308333bf39c1526fe1a893b0969f300b3d",
          "sha256": "15d7120a952238d265c95dde658ab9cf7aae78400f4d79deb0858ddb03881f5c",
          "sha1": "84f85ba8ab8e4d39f0d0dec483c39f4d7aaaf808",
          "md5": "138257d2513a6f6dc1432a19bcd5517e"
        }
      ]
    }
  ]
}
