{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saltedge.authenticator",
    "module": "sdk_v2",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.saltedge.authenticator",
          "module": "sdk_core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_v2-2.3.1.aar",
          "url": "sdk_v2-2.3.1.aar",
          "size": 113477,
          "sha512": "f2711d67ae1af618bac8ea1e63b0fbbbfe638b382fe9f9c5c195618fce406240ed511f66d9c07420928867222ea6b604b5286b35f811aa0cb56fefeefa86eaa2",
          "sha256": "8007bd7d61d03f9da239304ac334da5302df24ff0b97e7b297244c84966379d9",
          "sha1": "78602b46bcc7e45082a3e27de540b10412a476b1",
          "md5": "694c01b8a9f16a98884afa1fa2774608"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.saltedge.authenticator",
          "module": "sdk_core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_v2-2.3.1.aar",
          "url": "sdk_v2-2.3.1.aar",
          "size": 113477,
          "sha512": "f2711d67ae1af618bac8ea1e63b0fbbbfe638b382fe9f9c5c195618fce406240ed511f66d9c07420928867222ea6b604b5286b35f811aa0cb56fefeefa86eaa2",
          "sha256": "8007bd7d61d03f9da239304ac334da5302df24ff0b97e7b297244c84966379d9",
          "sha1": "78602b46bcc7e45082a3e27de540b10412a476b1",
          "md5": "694c01b8a9f16a98884afa1fa2774608"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_v2-2.3.1-sources.jar",
          "url": "sdk_v2-2.3.1-sources.jar",
          "size": 37743,
          "sha512": "09a4df8593c1d5e86b49fa422ed78341c0cc94d2e6e420521f3c08af0c141557528a84a68d03f03ac64bde07c1553a23043897ff55fd3833f1279ac74bec24b9",
          "sha256": "c92194f08af5b92308f23127c22573bdcdfbb3afd8871ef92e568940e8333109",
          "sha1": "314be96864e8efb44fbe2e8e6be17447cfa52754",
          "md5": "49983d7550add5edea13e4bfac5158a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_v2-2.3.1-javadoc.jar",
          "url": "sdk_v2-2.3.1-javadoc.jar",
          "size": 508872,
          "sha512": "1bfc1aa51c70a39562df56b5e72d50d041f2f10754ef2a13fed2a2623e890087d5b4e3e5af1294e06bade6ebbd3ef24fc06ef3bce9f06a7998c85bddc80f8c6b",
          "sha256": "4f10ae008213b84a287a556a469c2b3f8c56ce09a276bdd21d8f8d3dc6718104",
          "sha1": "c9b5d69d32facce06433288f1f638ceed7ef111a",
          "md5": "d8b995806c3fc471715b7142d934c806"
        }
      ]
    }
  ]
}
