{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saltedge.authenticator",
    "module": "sdk_core",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_core-1.3.0.aar",
          "url": "sdk_core-1.3.0.aar",
          "size": 96633,
          "sha512": "c816894539e956446ffba83bfef7000ff8b60f1244f2074f6329c297cb67abdd58483a1fbbe2cb1b136b6cadd04f86ca57119d4d9fd2c4481ee9e180d7e9e78a",
          "sha256": "df002016a8b1b3ccff3d2390f9d4e308e2f1f2a04690612e354ecc5859156445",
          "sha1": "09332014edcf62a854669f5aabb6557a89e1aa13",
          "md5": "b1db1871669375e4cbcb3de5d012e70c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_core-1.3.0.aar",
          "url": "sdk_core-1.3.0.aar",
          "size": 96633,
          "sha512": "c816894539e956446ffba83bfef7000ff8b60f1244f2074f6329c297cb67abdd58483a1fbbe2cb1b136b6cadd04f86ca57119d4d9fd2c4481ee9e180d7e9e78a",
          "sha256": "df002016a8b1b3ccff3d2390f9d4e308e2f1f2a04690612e354ecc5859156445",
          "sha1": "09332014edcf62a854669f5aabb6557a89e1aa13",
          "md5": "b1db1871669375e4cbcb3de5d012e70c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_core-1.3.0-sources.jar",
          "url": "sdk_core-1.3.0-sources.jar",
          "size": 34636,
          "sha512": "0117707025e4f5cd445bda6ecf05d8458344422067f136cd7a946e7904536bf7db5f26f18e518f2b41cf8b9c4d8cc5e0ebf3fbc2f3c008ec90a6b8c707a4a3b8",
          "sha256": "9a3091299f71aa84fcb53923ce0b423c6d058e7fdb24df500e76982081eb39f6",
          "sha1": "69a3a70e97b42de0cbc6b8a7aa6ca6320128043a",
          "md5": "5170172167802a457137945fd4b0820c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_core-1.3.0-javadoc.jar",
          "url": "sdk_core-1.3.0-javadoc.jar",
          "size": 575181,
          "sha512": "329792c6cca70cdf314c5a7efd0ed3d4ea59e0f31c2f31104422e05bb27090e3b29983f04e2ba46a9950c7b3122053922aedc8aee945eea122e05cf02d006cb5",
          "sha256": "3ea7b6a221b911421b6e16dae8e0514ddcc73617bbfe6bcfe35a4ee501a5a405",
          "sha1": "582751787ea8c9a7af9f9f9e1e6f6164cdb56747",
          "md5": "7e004f94ffd57f4ca87c3b807802e0e6"
        }
      ]
    }
  ]
}
