{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saltedge.authenticator",
    "module": "sdk_v2",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.saltedge.authenticator",
          "module": "sdk_core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_v2-2.1.0.aar",
          "url": "sdk_v2-2.1.0.aar",
          "size": 103869,
          "sha512": "d86b1b9c9edb703e7f6c4b64f88374503e0243a292bf0771895f78e116865b310fb63f9c5d92cb6a667c5d3d60ce5d70f8647b8f15aefde29b55d72f03ef4658",
          "sha256": "ac4df40a852d61b3310b3062bf0ca969857533a9007a78e8264d4c322cb52c70",
          "sha1": "376eb43736ca156a0c335c910f24d48efc114241",
          "md5": "d3efe7c2d0d5235ddf86d16c4ee67248"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.saltedge.authenticator",
          "module": "sdk_core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_v2-2.1.0.aar",
          "url": "sdk_v2-2.1.0.aar",
          "size": 103869,
          "sha512": "d86b1b9c9edb703e7f6c4b64f88374503e0243a292bf0771895f78e116865b310fb63f9c5d92cb6a667c5d3d60ce5d70f8647b8f15aefde29b55d72f03ef4658",
          "sha256": "ac4df40a852d61b3310b3062bf0ca969857533a9007a78e8264d4c322cb52c70",
          "sha1": "376eb43736ca156a0c335c910f24d48efc114241",
          "md5": "d3efe7c2d0d5235ddf86d16c4ee67248"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_v2-2.1.0-sources.jar",
          "url": "sdk_v2-2.1.0-sources.jar",
          "size": 35178,
          "sha512": "e6abd51f6384771ce951b77e31e818f49cc988c06730f17210c3010922eaeb36d95a79b867c870d85421a4551b246a674a2c7c8d020503c77c7b4094ba57bbb5",
          "sha256": "0836828a471c5c50b3a9957fb90fba9c1c133c80be520cfa588ae0b124cae7e5",
          "sha1": "79d19f52f5ab55278e200250fe731bf8b8109960",
          "md5": "9dc801de5dca760a41946e3996843e4d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_v2-2.1.0-javadoc.jar",
          "url": "sdk_v2-2.1.0-javadoc.jar",
          "size": 492646,
          "sha512": "ab5ca084df9ce1115e2fe29cf1088857713cb287d823f5026df042c2013ae2905923c2612d53c0edbecd7283840b8503a18c9faaf079c916087fbe6a99b06d78",
          "sha256": "89bd99c35f59bd6ff0728bc0a7a28c8f35d41f45e70d2f4a425ab7fd2d28c16b",
          "sha1": "837a5be2a89209cafc9c0effbf9bd7dab6f03a70",
          "md5": "31f8aa6d11998256f97d754380afa37a"
        }
      ]
    }
  ]
}
