{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saltedge.authenticator",
    "module": "sdk_v2",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.saltedge.authenticator",
          "module": "sdk_core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_v2-2.2.0.aar",
          "url": "sdk_v2-2.2.0.aar",
          "size": 113480,
          "sha512": "ffa4d8a589a86dd8c872e2f831ed757b307c5018038a585b63d5995475ceaa5ebb1cc3de7651b257af24efce5b1d02e3db9de4292f5a99af2344c250653a91a8",
          "sha256": "e977af6db456bae726827f74af01459e2309d986661c242518b20fff2b1a4935",
          "sha1": "2467fd92434b9764e5682e643a416f9eb0d9cb72",
          "md5": "a97e2f9f7dcc0a737bd6021c2b660eec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.saltedge.authenticator",
          "module": "sdk_core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_v2-2.2.0.aar",
          "url": "sdk_v2-2.2.0.aar",
          "size": 113480,
          "sha512": "ffa4d8a589a86dd8c872e2f831ed757b307c5018038a585b63d5995475ceaa5ebb1cc3de7651b257af24efce5b1d02e3db9de4292f5a99af2344c250653a91a8",
          "sha256": "e977af6db456bae726827f74af01459e2309d986661c242518b20fff2b1a4935",
          "sha1": "2467fd92434b9764e5682e643a416f9eb0d9cb72",
          "md5": "a97e2f9f7dcc0a737bd6021c2b660eec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_v2-2.2.0-sources.jar",
          "url": "sdk_v2-2.2.0-sources.jar",
          "size": 37711,
          "sha512": "34224a06ae48ac42fbc4dbb4e7b8b75855e8670d3dd448079a94d12417c0253fbd8fd47c478ce374bc1c4d97d093572e6b906d0fb348b9dc77ff8150b20b3107",
          "sha256": "48b6df5013151e389b9bf1575e5d1509efd6c81f72fce1a2e598be69bc165c5e",
          "sha1": "89ad5ee290280e3bcaa9f05b3534029b1ba1c9e4",
          "md5": "0bbae362d098857942c9a96fc66512b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_v2-2.2.0-javadoc.jar",
          "url": "sdk_v2-2.2.0-javadoc.jar",
          "size": 508752,
          "sha512": "5dfe9a42b52917adb447e67ab8c0c737f711185cde13b4c1c9589a64ff8035debf636cc1451efaa00cf2f369834074de73058f1ab4faed1386576d0d5b98f087",
          "sha256": "59667fdaca2bcae9e58ffdec0ae4476b0a10211a8a2c120ae3f87c193c700b68",
          "sha1": "ef706e61886175e64886d27268598abdf7f01f86",
          "md5": "ca3a05f5ef4a39931b9b984a7531b38b"
        }
      ]
    }
  ]
}
